identity:
  providers:
    - file:
        name: users
#   - ldap:
#        uri: <ldap_uri>
#        baseDn: dc=snowowl,dc=b2international,dc=com
#        rootDn: cn=admin,dc=snowowl,dc=b2international,dc=com
#        rootDnPassword: <adminpwd>
#        userIdProperty: uid
#        usePool: false

snomed:
  languages:
    -
      code: en
      refSetIds: ["900000000000509007", "900000000000508004"]
    -
      code: en-us
      refSetIds: ["900000000000509007"]
    -
      code: en-gb
      refSetIds: ["900000000000508004"]

monitoring:
  enabled: true

