#
# Copyright 2011-2021 B2i Healthcare Pte Ltd, http://b2i.sg
#

identity:
#  jws: HS256
#  secret: <your-secret>
  providers:
    - file:
        name: users
#   - ldap:
#        uri: <ldap_uri>
#        baseDn: dc=snowowl,dc=b2international,dc=com
#        rootDn: cn=admin,dc=snowowl,dc=b2international,dc=com
#        rootDnPassword: <adminpwd>
#        userIdProperty: uid
#        usePool: false

monitoring:
  enabled: true

