name: Java CI

on:
  push:
    branches:
      - 7.x
      - 8.x
  pull_request:
    branches:
      - 7.x
      - 8.x

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.3
    - name: Set up JDK 17
      uses: actions/setup-java@v2.2.0
      with:
        distribution: temurin
        java-version: 17
    - name: Cache Maven Dependencies (~/.m2/repository)
      uses: actions/cache@v2.1.2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-:
    - name: Cache NPM Dependencies (core/com.b2international.snowowl.core.rest/snow-owl-api-docs/node_modules)
      uses: actions/cache@v2.1.2
      with:
        path: core/com.b2international.snowowl.core.rest/snow-owl-api-docs/node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('core/com.b2international.snowowl.core.rest/snow-owl-api-docs/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-:
    - name: Setup Maven settings.xml
      uses: whelk-io/maven-settings-xml-action@v14
      with:
        servers: '[{ "id": "b2i-releases", "username": "${env.NEXUS_DEPLOYMENT_USER}", "password": "${env.NEXUS_DEPLOYMENT_PASS}" }, { "id": "b2i-snapshots", "username": "${env.NEXUS_DEPLOYMENT_USER}", "password": "${env.NEXUS_DEPLOYMENT_PASS}" }, { "id": "nexus_deployment", "username": "${env.NEXUS_DEPLOYMENT_USER}", "password": "${env.NEXUS_DEPLOYMENT_PASS}" }]'
    - name: Build with Maven
      run: mvn -ntp clean verify
      env: 
        NEXUS_DEPLOYMENT_USER: ${{ secrets.NEXUS_DEPLOYMENT_USER }}
        NEXUS_DEPLOYMENT_PASS: ${{ secrets.NEXUS_DEPLOYMENT_PASS }}
    - name: Upload Codecov
      uses: codecov/codecov-action@v1.3.2
      with:
        fail_ci_if_error: true
